const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='english-structure-lab-v1';
const blank=()=>({version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:{theme:'dark'},mastery:{},attemptHistory:[],reading:{},journal:[],eventLog:[],sessionCount:0,lastLesson:'center'});
let state=load(),curriculum=[],lessons=[],passages=[],images=[],activeLesson='center',activePassage='r1',activeRole='S';
let pen={color:'#1f2937',eraser:false,drawing:false,stroke:null};
function load(){try{return {...blank(),...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return blank()}}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));$('#saveState').textContent='保存済み '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}
function log(type,data={}){state.eventLog.push({id:crypto.randomUUID?.()||String(Date.now()),time:new Date().toISOString(),type,...data});if(state.eventLog.length>2000)state.eventLog=state.eventLog.slice(-2000);save()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.x);toast.x=setTimeout(()=>el.classList.remove('show'),1700)}
function mastery(id){return state.mastery[id]?.score||0}
function nextStep(){return curriculum.steps.find(x=>mastery(x.id)<70)||curriculum.steps.at(-1)}
async function init(){[curriculum,lessons,passages,images]=await Promise.all(['curriculum','lessons','reading','core-images'].map(x=>fetch(`./data/${x}.json`).then(r=>r.json())));activeLesson=state.lastLesson||'center';bind();renderAll();setupCanvas();state.sessionCount++;log('session_start');}
function bind(){
  $$('.nav-item').forEach(b=>b.onclick=()=>openView(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>openView(b.dataset.viewJump));$$('[data-open-export]').forEach(b=>b.onclick=()=>openView('export'));
  $('#continueBtn').onclick=()=>{openView('lesson');selectLesson(state.lastLesson||nextStep().lessonId)};$('#themeToggle').onclick=()=>{state.settings.theme=state.settings.theme==='light'?'dark':'light';applyTheme();save()};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
  $('#passageSelect').onchange=e=>{activePassage=e.target.value;ensureReading();renderReading();setTimeout(()=>{resizeCanvas();renderInk()},10)};
  $$('.role-btn').forEach(b=>b.onclick=()=>{activeRole=b.dataset.role;$$('.role-btn').forEach(x=>x.classList.toggle('active',x===b))});
  ['firstHypothesis','confusionMemo','correctionMemo'].forEach(id=>$('#'+id).addEventListener('change',()=>saveNote(id)));
  $('#confidence').oninput=e=>$('#confidenceValue').textContent=e.target.value;$('#revisionBtn').onclick=revision;$('#checkReadingBtn').onclick=checkReading;
  $('#saveJournalBtn').onclick=saveJournal;$('#addJournalBtn').onclick=()=>$('#journalTitle').focus();$('#downloadJsonBtn').onclick=downloadJson;$('#copyPromptBtn').onclick=copyPrompt;$('#importJson').onchange=importJson;$('#resetDataBtn').onclick=resetData;
  $$('.pen-tool[data-pen-color]').forEach(b=>b.onclick=()=>{pen.color=b.dataset.penColor;pen.eraser=false;$$('.pen-tool').forEach(x=>x.classList.toggle('active',x===b));$('#eraserBtn').classList.remove('active')});$('#eraserBtn').onclick=()=>{pen.eraser=!pen.eraser;$('#eraserBtn').classList.toggle('active',pen.eraser)};$('#undoInkBtn').onclick=undoInk;$('#clearInkBtn').onclick=clearInk;
  addEventListener('resize',()=>{resizeCanvas();renderInk()});
}
function openView(n){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${n}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===n));const t={home:['TODAY','今日の学習'],roadmap:['ROADMAP','理解ロード'],lesson:['CORE LESSONS','本質レッスン'],reading:['READING LAB','長文・構造分析'],images:['CORE IMAGE','単語イメージ'],journal:['LEARNING JOURNAL','思考メモ'],export:['CHATGPT HANDOFF','ChatGPT提出']}[n];$('#viewEyebrow').textContent=t[0];$('#viewTitle').textContent=t[1];if(n==='export')renderExport();if(n==='reading')setTimeout(()=>{resizeCanvas();renderInk()},20);scrollTo({top:0,behavior:'smooth'});if(innerWidth<720)$('#sidebar').classList.remove('open')}
function applyTheme(){document.body.classList.toggle('light',state.settings?.theme==='light')}
function renderAll(){applyTheme();$('#sessionCount').textContent=state.sessionCount;renderAbilities();renderRoadmap();renderLessonNav();selectLesson(activeLesson);renderPassageSelect();renderReading();renderImages();renderJournal();renderRecent();renderExport()}
function renderAbilities(){const a=[['sv','S/V'],['patterns','文型'],['modifiers','修飾'],['tense','時制'],['reading','長文']];$('#abilityList').innerHTML=a.map(([id,n])=>`<div class="ability-row"><span>${n}</span><div class="bar"><span style="width:${mastery(id)}%"></span></div><strong>${mastery(id)}%</strong></div>`).join('')}
function renderRoadmap(){const next=nextStep().id;$('#roadmapList').innerHTML=curriculum.steps.map(s=>{const sc=mastery(s.id),cl=sc>=70?'done':s.id===next?'current':'';return `<article class="roadmap-item ${cl}" data-lesson="${s.lessonId}"><span class="roadmap-num">${String(s.order).padStart(2,'0')}</span><div class="roadmap-copy"><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p></div><span class="roadmap-status">${sc?sc+'%':'未判定'}</span></article>`}).join('');$$('.roadmap-item').forEach(x=>x.onclick=()=>{openView('lesson');selectLesson(x.dataset.lesson)})}
function renderLessonNav(){$('#lessonNav').innerHTML=lessons.map((l,i)=>`<button data-lesson="${l.id}">${String(i+1).padStart(2,'0')} ${esc(l.title)}</button>`).join('');$$('#lessonNav button').forEach(b=>b.onclick=()=>selectLesson(b.dataset.lesson))}
function selectLesson(id){activeLesson=id;state.lastLesson=id;save();$$('#lessonNav button').forEach(b=>b.classList.toggle('active',b.dataset.lesson===id));const l=lessons.find(x=>x.id===id)||lessons[0];$('#lessonMain').innerHTML=`<article class="panel lesson-card"><span class="eyebrow">${l.tag} · ${mastery(id)}% MASTERED</span><h2>${esc(l.title)}</h2><p class="lead">${esc(l.lead)}</p><div class="concept-box"><strong>核になる考え方</strong><div>${esc(l.core)}</div></div>${l.examples.map(e=>`<div class="example"><div class="en">${esc(e.en)}</div><div class="why">${esc(e.why)}</div></div>`).join('')}</article><article class="panel quiz-card"><span class="eyebrow">QUICK CHECK</span><h3>理解チェック</h3><div class="quiz-question">${esc(l.quiz.question)}</div><div class="options">${l.quiz.options.map((o,i)=>`<button class="option-btn" data-i="${i}">${esc(o)}</button>`).join('')}</div><div class="quiz-explain hidden" id="quizExplain"></div></article>`;$$('.option-btn',$('#lessonMain')).forEach(b=>b.onclick=()=>answerQuiz(l,+b.dataset.i))}
function answerQuiz(l,a){const ok=a===l.quiz.answer;$$('.option-btn',$('#lessonMain')).forEach((b,i)=>{b.disabled=true;if(i===l.quiz.answer)b.classList.add('correct');if(i===a&&!ok)b.classList.add('wrong')});const ex=$('#quizExplain');ex.classList.remove('hidden');ex.textContent=(ok?'正解。 ':'違います。 ')+l.quiz.explain;state.attemptHistory.push({id:crypto.randomUUID(),time:new Date().toISOString(),type:'lesson_quiz',lessonId:l.id,question:l.quiz.question,selected:a,selectedText:l.quiz.options[a],correctAnswer:l.quiz.answer,correct:ok});const m=state.mastery[l.id]||{score:0,attempts:0,correct:0};m.attempts++;if(ok)m.correct++;m.score=Math.round(m.correct/m.attempts*100);m.lastAttemptAt=new Date().toISOString();state.mastery[l.id]=m;log('lesson_answer',{lessonId:l.id,selected:a,correct:ok});renderAbilities();renderRoadmap();renderRecent();toast(ok?'正解':'間違い方も保存しました')}
function renderPassageSelect(){$('#passageSelect').innerHTML=passages.map(p=>`<option value="${p.id}">${p.level}｜${esc(p.title)}</option>`).join('');$('#passageSelect').value=activePassage}
function ensureReading(){if(!state.reading[activePassage])state.reading[activePassage]={annotations:{},annotationHistory:[],firstHypothesis:'',confusionMemo:'',correctionMemo:'',confidence:3,revisions:[],checks:[],penStrokes:[]};return state.reading[activePassage]}
function tokens(t){return t.match(/[A-Za-z]+(?:'[A-Za-z]+)?|\d+|[^\sA-Za-z\d]/g)||[]}
function renderReading(){const p=passages.find(x=>x.id===activePassage)||passages[0],r=ensureReading();$('#passageMeta').innerHTML=`<strong>${p.level}</strong> · ${esc(p.focus)} · ${esc(p.source)}`;$('#passageText').innerHTML=p.sentences.map((s,si)=>`<span class="sentence-row">${tokens(s.text).map((w,wi)=>{const k=`${si}:${wi}`,role=r.annotations[k];return `<span class="word-token" data-key="${k}" ${role?`data-role="${role}"`:''}>${esc(w)}</span>`}).join(' ')}</span>`).join('');$$('.word-token').forEach(t=>t.onclick=()=>annotate(t));$('#firstHypothesis').value=r.firstHypothesis;$('#confusionMemo').value=r.confusionMemo;$('#correctionMemo').value=r.correctionMemo;$('#confidence').value=r.confidence||3;$('#confidenceValue').textContent=r.confidence||3;$('#readingFeedback').classList.add('hidden');renderReadingStats()}
function annotate(el){const r=ensureReading(),k=el.dataset.key,old=r.annotations[k]||null,next=activeRole||null;if(next)r.annotations[k]=next;else delete r.annotations[k];r.annotationHistory.push({time:new Date().toISOString(),tokenKey:k,token:el.textContent,from:old,to:next});if(next)el.dataset.role=next;else el.removeAttribute('data-role');log('reading_annotation_change',{passageId:activePassage,tokenKey:k,token:el.textContent,from:old,to:next});renderReadingStats()}
function saveNote(id){const map={firstHypothesis:'firstHypothesis',confusionMemo:'confusionMemo',correctionMemo:'correctionMemo'},r=ensureReading(),f=map[id],old=r[f],v=$('#'+id).value;r[f]=v;log('reading_note_edit',{passageId:activePassage,field:f,previous:old,newValue:v})}
function revision(){const r=ensureReading();r.confidence=+$('#confidence').value;r.revisions.push({time:new Date().toISOString(),annotationSnapshot:{...r.annotations},firstHypothesis:r.firstHypothesis,confusionMemo:r.confusionMemo,correctionMemo:r.correctionMemo,confidence:r.confidence});log('reading_revision',{passageId:activePassage,revisionNumber:r.revisions.length,confidence:r.confidence});renderReadingStats();toast('読み直しを記録しました')}
function expected(p){const out={};p.sentences.forEach((s,si)=>{let ri=0;tokens(s.text).forEach((w,wi)=>{if(/^[A-Za-z0-9]/.test(w)){const role=s.roles[ri]?.[1];if(role)out[`${si}:${wi}`]=role;ri++}})});return out}
function checkReading(){const p=passages.find(x=>x.id===activePassage),r=ensureReading(),e=expected(p);let total=0,correct=0,wrong=[];for(const [k,v] of Object.entries(e)){total++;const got=r.annotations[k]||null;if(got===v)correct++;else wrong.push({key:k,expected:v,selected:got})}const score=Math.round(correct/total*100);r.confidence=+$('#confidence').value;r.checks.push({time:new Date().toISOString(),score,correct,total,wrong,annotationSnapshot:{...r.annotations},confidence:r.confidence,notes:{first:r.firstHypothesis,confusion:r.confusionMemo,correction:r.correctionMemo}});const m=state.mastery.reading||{score:0,attempts:0};m.attempts++;m.score=Math.round((m.score*(m.attempts-1)+score)/m.attempts);state.mastery.reading=m;log('reading_check',{passageId:activePassage,score,wrongCount:wrong.length,confidence:r.confidence});const f=$('#readingFeedback');f.classList.remove('hidden');f.innerHTML=`<strong>構造一致率 ${score}%</strong><br>${score>=80?'骨格はかなり安定しています。':'一致していない箇所があります。変更履歴もJSONに保存されています。'}<br><span class="muted">初版は主節中心の簡略判定。節内部の階層判定は今後拡張します。</span>`;renderAbilities();renderRoadmap();renderReadingStats();renderRecent()}
function renderReadingStats(){const r=ensureReading();$('#readingStats').innerHTML=`<div class="mini-stat"><strong>${Object.keys(r.annotations).length}</strong><span>構造ラベル</span></div><div class="mini-stat"><strong>${r.annotationHistory.length}</strong><span>ラベル変更</span></div><div class="mini-stat"><strong>${r.revisions.length}</strong><span>読み直し</span></div><div class="mini-stat"><strong>${r.checks.at(-1)?.score??'-'}${r.checks.length?'%':''}</strong><span>最新一致率</span></div>`}
function renderImages(){$('#imageWordGrid').innerHTML=images.map(w=>`<article class="panel image-word-card"><div class="word-head"><h3>${w.word}</h3><span>${w.label}</span></div><div class="core-visual">${esc(w.core)}</div><p class="core-desc">${esc(w.desc)}</p><div class="word-examples">${w.examples.map(x=>`<div><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('')}</div></article>`).join('')}
function saveJournal(){const title=$('#journalTitle').value.trim(),body=$('#journalBody').value.trim();if(!title&&!body)return toast('メモを入力してください');const j={id:crypto.randomUUID(),time:new Date().toISOString(),title:title||'無題メモ',body,type:$('#journalType').value};state.journal.unshift(j);log('journal_added',{journalId:j.id,title:j.title,type:j.type});$('#journalTitle').value='';$('#journalBody').value='';renderJournal();renderRecent()}
function renderJournal(){$('#journalList').innerHTML=state.journal.length?state.journal.map(j=>`<article class="journal-item"><span class="eyebrow">${esc(j.type)}</span><h3>${esc(j.title)}</h3><p>${esc(j.body)}</p><span class="muted">${new Date(j.time).toLocaleString('ja-JP')}</span></article>`).join(''):'<div class="empty-state">疑問・勘違い・自分なりの理解を残すと、ChatGPTが読み方の癖を追いやすくなります。</div>'}
function renderRecent(){const e=[...state.eventLog].reverse().filter(x=>['lesson_answer','reading_annotation_change','reading_revision','reading_check','journal_added'].includes(x.type)).slice(0,6);$('#recentTrace').innerHTML=e.length?e.map(x=>`<div class="trace-item"><span class="trace-time">${new Date(x.time).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span><div class="trace-main"><strong>${esc(x.type)}</strong><span>${esc(x.token||x.title||x.lessonId||x.passageId||'学習ログ')}</span></div><span class="trace-tag">記録</span></div>`).join(''):'<div class="empty-state">まだログはありません。</div>'}
function handoff(){return `添付した learning-data.json は英語学習サイトの学習ログです。\n\n最終スコアだけでなく、attemptHistory、reading.annotationHistory、reading.revisions、firstHypothesis / confusionMemo / correctionMemo、journal、eventLog を見てください。\n\n目的は、間違えた問題を再出題するだけでなく、私の読み方・考え方の癖と、どの基礎概念まで戻れば修正できるかを特定することです。\n\n説明は幼くしすぎず、本質・構造・理由を論理的に。分かっている所は繰り返さず、弱い部分を1段階ずつ積み上げてください。単語・前置詞はできるだけ日本語訳の丸暗記ではなく核イメージから説明してください。\n\n最後に、次に学ぶ項目、復習項目、サイトへ追加するとよい練習形式を提案してください。`}
function exportObj(){return {schema:'english-structure-lab-learning-data',schemaVersion:1,exportedAt:new Date().toISOString(),learningPolicy:{goal:'英語を基礎概念から積み上げ、本質・構造・核イメージで理解する',readingPriority:'訳す前にS/Vと節構造を取る',vocabularyPriority:'日本語訳より核イメージを優先',learnerNote:'基礎から確認するが説明を幼くしない。理解済みは早送りする。'},mastery:state.mastery,attemptHistory:state.attemptHistory,reading:state.reading,journal:state.journal,eventLog:state.eventLog,meta:{createdAt:state.createdAt,updatedAt:state.updatedAt,sessionCount:state.sessionCount,lastLesson:state.lastLesson},chatgptAnalysisRequest:handoff()}}
function renderExport(){const changes=Object.values(state.reading).reduce((n,r)=>n+r.annotationHistory.length,0),revs=Object.values(state.reading).reduce((n,r)=>n+r.revisions.length,0);$('#exportSummary').innerHTML=`<div><span>問題回答</span><strong>${state.attemptHistory.length}</strong></div><div><span>構造ラベル変更</span><strong>${changes}</strong></div><div><span>読み直し</span><strong>${revs}</strong></div><div><span>思考メモ</span><strong>${state.journal.length}</strong></div>`;$('#handoffPrompt').value=handoff()}
function downloadJson(){const a=document.createElement('a'),b=new Blob([JSON.stringify(exportObj(),null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download=`english_learning_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);log('json_exported');toast('JSONを書き出しました')}
async function copyPrompt(){await navigator.clipboard.writeText(handoff());toast('依頼文をコピーしました')}
async function importJson(e){const f=e.target.files?.[0];if(!f)return;try{const o=JSON.parse(await f.text());if(o.schema==='english-structure-lab-learning-data'){state={...blank(),mastery:o.mastery||{},attemptHistory:o.attemptHistory||[],reading:o.reading||{},journal:o.journal||[],eventLog:o.eventLog||[],sessionCount:o.meta?.sessionCount||0,lastLesson:o.meta?.lastLesson||'center',settings:state.settings}}else state={...blank(),...o};save();renderAll();toast('JSONを読み込みました')}catch{toast('JSONを読み込めませんでした')}e.target.value=''}
function resetData(){if(!confirm('この端末の学習履歴・メモ・書き込みをすべて消しますか？'))return;localStorage.removeItem(KEY);state=blank();renderAll();toast('初期化しました')}
function setupCanvas(){const c=$('#inkCanvas');['pointerdown','pointermove','pointerup','pointercancel','pointerleave'].forEach(t=>c.addEventListener(t,pointer));resizeCanvas();renderInk()}
function resizeCanvas(){const c=$('#inkCanvas'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;if(!r.width)return;c.width=r.width*d;c.height=r.height*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}
function pt(e){const r=$('#inkCanvas').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,p:e.pointerType==='pen'?(e.pressure||.35):.45}}
function pointer(e){if(e.pointerType==='touch')return;if(e.type==='pointerdown'){e.preventDefault();pen.drawing=true;pen.stroke={id:crypto.randomUUID(),time:new Date().toISOString(),color:pen.color,eraser:pen.eraser,points:[pt(e)]};return}if(e.type==='pointermove'&&pen.drawing){e.preventDefault();pen.stroke.points.push(pt(e));renderInk();drawStroke(pen.stroke);return}if(['pointerup','pointercancel','pointerleave'].includes(e.type)&&pen.drawing){pen.drawing=false;if(pen.stroke.points.length>1){ensureReading().penStrokes.push(pen.stroke);log('pen_stroke',{passageId:activePassage,pointCount:pen.stroke.points.length,eraser:pen.stroke.eraser})}pen.stroke=null;renderInk()}}
function drawStroke(s){const c=$('#inkCanvas'),ctx=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.globalCompositeOperation=s.eraser?'destination-out':'source-over';ctx.strokeStyle=s.color;for(let i=1;i<s.points.length;i++){const a=s.points[i-1],b=s.points[i];ctx.beginPath();ctx.lineWidth=s.eraser?18:1.3+4*(b.p||.4);ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke()}ctx.restore()}
function renderInk(){const c=$('#inkCanvas');if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.clientWidth,c.clientHeight);(ensureReading().penStrokes||[]).forEach(drawStroke)}
function undoInk(){const r=ensureReading(),s=r.penStrokes.pop();if(s){log('pen_undo',{passageId:activePassage,strokeId:s.id});renderInk()}}
function clearInk(){const r=ensureReading();if(!r.penStrokes.length)return;if(confirm('この長文のペン書き込みを全消去しますか？')){log('pen_clear',{passageId:activePassage,count:r.penStrokes.length});r.penStrokes=[];save();renderInk()}}
init().catch(e=>{console.error(e);document.body.innerHTML=`<pre style="padding:30px;color:white">読み込みエラー: ${esc(e.message)}\nGitHub Pagesから開いてください。</pre>`});
