function setupCanvas(){const c=$('#inkCanvas');['pointerdown','pointermove','pointerup','pointercancel','pointerleave'].forEach(t=>c.addEventListener(t,onPointer))}
function setMode(next,rerender=true){mode='pen';const p=$('#paper');if(p)p.classList.add('pen-mode');if(rerender){resizeCanvas();renderInk()}}
function resizeCanvas(){const c=$('#inkCanvas'),paper=$('#paper');if(!c||!paper||$('#practiceArea').classList.contains('hidden'))return;const d=devicePixelRatio||1,w=paper.clientWidth,h=paper.scrollHeight;c.style.width=w+'px';c.style.height=h+'px';c.width=Math.max(1,Math.floor(w*d));c.height=Math.max(1,Math.floor(h*d));c.getContext('2d').setTransform(d,0,0,d,0,0)}
function point(e){const r=$('#inkCanvas').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,p:e.pointerType==='pen'?(e.pressure||.35):.45}}
function questionAtPoint(pt){const paper=$('#paper').getBoundingClientRect(),y=pt.y*paper.height;for(const q of $$('.question')){const r=q.getBoundingClientRect(),top=r.top-paper.top,bottom=r.bottom-paper.top;if(y>=top&&y<=bottom)return q.dataset.questionId}return null}
function onPointer(e){if(e.pointerType==='touch')return;const c=$('#inkCanvas');if(e.type==='pointerdown'){e.preventDefault();c.setPointerCapture?.(e.pointerId);pen.drawing=true;const p=point(e);pen.stroke={id:id(),time:new Date().toISOString(),color:pen.color,eraser:pen.eraser,questionId:questionAtPoint(p),points:[p]};return}if(e.type==='pointermove'&&pen.drawing){e.preventDefault();pen.stroke.points.push(point(e));renderInk();drawStroke(pen.stroke);return}if(['pointerup','pointercancel','pointerleave'].includes(e.type)&&pen.drawing){pen.drawing=false;if(pen.stroke.points.length>1){const pr=progress();pr.inkPages[currentPage]??=[];pr.inkPages[currentPage].push(pen.stroke);save()}const qid=pen.stroke?.questionId;pen.stroke=null;renderInk();updatePracticeProgress();if(qid){const q=$(`.question[data-question-id="${qid}"] .q-status`);if(q)q.textContent=`手書き ${inkCountForQuestion(progress(),qid)}ストローク`}}}
function drawStroke(s){const c=$('#inkCanvas'),ctx=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.globalCompositeOperation=s.eraser?'destination-out':'source-over';ctx.strokeStyle=s.color;for(let i=1;i<s.points.length;i++){const a=s.points[i-1],b=s.points[i];ctx.beginPath();ctx.lineWidth=s.eraser?19:1.25+4.5*(b.p||.4);ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke()}ctx.restore()}
function renderInk(){const c=$('#inkCanvas');if(!c||!state.activePackId)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.clientWidth,c.clientHeight);(progress().inkPages[currentPage]||[]).forEach(drawStroke)}
function undoInk(){const arr=progress()?.inkPages[currentPage];if(arr?.length){arr.pop();save();renderInk();renderPractice();toast('1ストローク戻しました')}}
function clearInk(){const arr=progress()?.inkPages[currentPage];if(!arr?.length)return;if(confirm('このページのペン書き込みをすべて消しますか？')){progress().inkPages[currentPage]=[];save();renderPractice();toast('ページの書き込みを消しました')}}
