const PEN_SIZE_FACTOR={thin:.68,normal:1,thick:1.48};
function ensureInkExtras(pr=progress()){if(!pr)return pr;pr.redoPages??={};pr.clearHistory??={};return pr}
function setMode(){mode='pen';const p=$('#paper');if(p){p.classList.add('pen-mode');p.classList.toggle('eraser-cursor',!!pen.eraser);p.classList.toggle('marker-cursor',pen.tool==='marker')}resizeCanvas();renderInk()}
function setupCanvas(){const c=$('#inkCanvas');if(!c)return;['pointerdown','pointermove','pointerup','pointercancel'].forEach(t=>c.addEventListener(t,onPointer,{passive:false}));c.addEventListener('contextmenu',e=>e.preventDefault())}
function resizeCanvas(){const c=$('#inkCanvas'),paper=$('#paper');if(!c||!paper||$('#practiceArea')?.classList.contains('hidden'))return;const d=Math.min(2,devicePixelRatio||1),w=paper.clientWidth,h=paper.scrollHeight;c.style.width=w+'px';c.style.height=h+'px';c.width=Math.max(1,Math.floor(w*d));c.height=Math.max(1,Math.floor(h*d));c.getContext('2d').setTransform(d,0,0,d,0,0)}
function rawPoint(e){const r=$('#inkCanvas').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,p:e.pointerType==='pen'?(e.pressure||.35):.45,t:performance.now()}}
function compactPoint(p,start){return{x:+Math.min(1,Math.max(0,p.x)).toFixed(5),y:+Math.min(1,Math.max(0,p.y)).toFixed(5),p:+Math.min(1,Math.max(.05,p.p||.35)).toFixed(3),dt:Math.max(0,Math.round(p.t-start))}}
function shouldAppend(last,p){if(!last)return true;const dx=p.x-last.x,dy=p.y-last.y;return dx*dx+dy*dy>0.0000006||p.t-(last.t||0)>18}
function questionAtPoint(pt){const paper=$('#paper').getBoundingClientRect(),y=pt.y*paper.height;for(const q of $$('.question')){const r=q.getBoundingClientRect(),top=r.top-paper.top,bottom=r.bottom-paper.top;if(y>=top&&y<=bottom)return q.dataset.questionId}return null}
function strokeEvents(e){try{const a=e.getCoalescedEvents?.();return a?.length?a:[e]}catch{return[e]}}
function onPointer(e){if(e.pointerType==='touch')return;const c=$('#inkCanvas');if(e.type==='pointerdown'){if(e.button!=null&&e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();c.setPointerCapture?.(e.pointerId);pen.drawing=true;const p=rawPoint(e),start=performance.now();pen.stroke={id:id(),time:new Date().toISOString(),startedMs:start,color:pen.color,eraser:!!pen.eraser,tool:pen.eraser?'eraser':(pen.tool||'pen'),size:pen.size||'normal',pointerType:e.pointerType,questionId:questionAtPoint(p),points:[p]};return}if(e.type==='pointermove'&&pen.drawing){e.preventDefault();for(const ev of strokeEvents(e)){const p=rawPoint(ev),last=pen.stroke.points.at(-1);if(shouldAppend(last,p))pen.stroke.points.push(p)}renderInk();drawStroke(pen.stroke);return}if(['pointerup','pointercancel'].includes(e.type)&&pen.drawing){e.preventDefault();pen.drawing=false;const s=pen.stroke;if(s&&s.points.length>1){s.points=s.points.map(p=>compactPoint(p,s.startedMs));delete s.startedMs;const pr=ensureInkExtras();pr.inkPages[currentPage]??=[];pr.inkPages[currentPage].push(s);pr.redoPages[currentPage]=[];save()}const qid=s?.questionId;pen.stroke=null;renderInk();updatePracticeProgress();if(qid){const q=$(`.question[data-question-id="${qid}"] .q-status`);if(q)q.textContent=`手書き ${inkCountForQuestion(progress(),qid)}ストローク`}}}
function drawStroke(s){const c=$('#inkCanvas');if(!c)return;const ctx=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,pts=s.points||[];if(pts.length<2)return;const factor=PEN_SIZE_FACTOR[s.size]||1;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';if(s.eraser||s.tool==='eraser'){ctx.globalCompositeOperation='destination-out';ctx.globalAlpha=1}else{ctx.globalCompositeOperation='source-over';ctx.strokeStyle=s.color||'#1f2937';ctx.globalAlpha=s.tool==='marker'?.28:1}for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];ctx.beginPath();ctx.lineWidth=(s.eraser||s.tool==='eraser')?22:(s.tool==='marker'?15:factor*(1.15+4.6*(b.p||.4)));ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke()}ctx.restore()}
function renderInk(){const c=$('#inkCanvas');if(!c||!state.activePackId)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.clientWidth,c.clientHeight);(ensureInkExtras().inkPages[currentPage]||[]).forEach(drawStroke)}
function undoInk(){const pr=ensureInkExtras(),arr=pr?.inkPages?.[currentPage]||[];if(arr.length){pr.redoPages[currentPage]??=[];pr.redoPages[currentPage].push(arr.pop());save();renderInk();updatePracticeProgress();toast('1ストローク戻しました');return}const clears=pr?.clearHistory?.[currentPage]||[];if(clears.length){const last=clears.pop();pr.inkPages[currentPage]=last.strokes||[];save();renderPractice();toast('ページ消去を元に戻しました');return}toast('戻せる書き込みがありません')}
function redoInk(){const pr=ensureInkExtras(),redo=pr?.redoPages?.[currentPage]||[];if(!redo.length)return toast('やり直せる線がありません');pr.inkPages[currentPage]??=[];pr.inkPages[currentPage].push(redo.pop());save();renderInk();updatePracticeProgress();toast('1ストロークやり直しました')}
function clearInk(){const pr=ensureInkExtras(),arr=pr?.inkPages?.[currentPage]||[];if(!arr.length)return;if(!confirm('このページのペン書き込みをすべて消しますか？\n「戻す」で直前のページ消去を復元できます。'))return;pr.clearHistory[currentPage]??=[];pr.clearHistory[currentPage].push({time:new Date().toISOString(),strokes:structuredClone(arr)});if(pr.clearHistory[currentPage].length>3)pr.clearHistory[currentPage]=pr.clearHistory[currentPage].slice(-3);pr.inkPages[currentPage]=[];pr.redoPages[currentPage]=[];save();renderPractice();toast('ページを消去しました。戻すで復元できます')}
