const MISTAKE_TAGS=[['subject','Sを取り違えた'],['verb','Vを取り違えた'],['clause','節の境界'],['modifier','修飾を骨格に入れた'],['oc','O/C・文型'],['tense','時制・時間軸'],['verbform','to / ing'],['preposition','前置詞イメージ'],['wordorder','語順'],['vocab','単語の意味'],['question','設問読み違い'],['unknown','分からなかった']];
let pageTimer=null;
function ensureProgressExtras(pr=progress()){if(!pr)return pr;pr.selfGrades??={};pr.reviewMode??=false;pr.reviewTags??={};pr.reviewNotes??={};pr.pageTimeMs??={};pr.redoPages??={};pr.clearHistory??={};pr.attemptId??=id();pr.startedAt??=new Date().toISOString();return pr}
function flushPageTimer(){if(!pageTimer)return;const pr=state.packProgress[pageTimer.packId];if(pr){pr.pageTimeMs??={};pr.pageTimeMs[pageTimer.page]=(pr.pageTimeMs[pageTimer.page]||0)+Math.max(0,performance.now()-pageTimer.started)}pageTimer=null}
function startPageTimer(){if(!state.activePackId)return;const pr=ensureProgressExtras();if(pageTimer&&pageTimer.packId===state.activePackId&&pageTimer.page===currentPage)return;flushPageTimer();pageTimer={packId:state.activePackId,page:currentPage,started:performance.now()};updatePageTimeLabel()}
function pageElapsedMs(pr=progress(),page=currentPage){const base=pr?.pageTimeMs?.[page]||0;return base+(pageTimer&&pageTimer.packId===state.activePackId&&pageTimer.page===page?performance.now()-pageTimer.started:0)}
function formatDuration(ms){const sec=Math.max(0,Math.round((ms||0)/1000)),m=Math.floor(sec/60),s=sec%60;return m?`${m}分${String(s).padStart(2,'0')}秒`:`${s}秒`}
function updatePageTimeLabel(){const el=$('#pageTimeLabel');if(el&&state.activePackId)el.textContent=`このページ ${formatDuration(pageElapsedMs())}`}
setInterval(()=>{if(pageTimer)updatePageTimeLabel()},1000);
function inkCountForQuestion(pr,qid){return Object.values(pr?.inkPages||{}).flat().filter(s=>s.questionId===qid&&!s.eraser&&s.tool!=='eraser').length}
function paperLines(count=4,compact=false){return `<div class="paper-writing-lines${compact?' compact':''}">${'<i></i>'.repeat(count)}</div>`}
function renderQuestion(q,num){const pr=ensureProgressExtras(),inkCount=inkCountForQuestion(pr,q.id);let answer='';if(q.type==='fields')answer=`<div class="paper-answer-lines">${(q.fields||[]).map(f=>`<div class="paper-line-field"><span>${esc(f.label)}</span><i></i></div>`).join('')}</div>`;else if(q.type==='choice')answer=`<div class="paper-choice-list">${(q.choices||[]).map((c,i)=>`<div><b>${String.fromCharCode(65+i)}.</b><span>${esc(c)}</span></div>`).join('')}</div>`;else if(q.type==='manual')answer=paperLines(q.lines||4);else if(q.type==='reorder')answer=`<div class="reorder-words">${(q.words||[]).map(w=>`<span class="reorder-word">${esc(w)}</span>`).join('')}</div>${paperLines(q.lines||2,true)}`;else if(q.type==='passage')answer=`<div class="passage-box">${esc(q.passage||'')}</div><div class="passage-tasks">${(q.tasks||[]).map((t,i)=>`<div class="passage-task"><b>${i+1}</b><span>${esc(t)}</span></div>`).join('')}</div>${paperLines(q.lines||6)}`;else answer=paperLines(q.lines||3);const grade=pr.selfGrades[q.id]||'';return `<section class="question ${inkCount?'ink-present':''}" data-question-id="${q.id}"><span class="q-num">${num}.</span><div class="q-prompt">${esc(q.prompt)}</div>${q.visual?`<div class="question-visual">${esc(q.visual)}</div>`:''}${q.sentence?`<div class="q-sentence">${esc(q.sentence)}</div>`:''}${answer}${q.note?`<div class="q-note">${esc(q.note)}</div>`:''}<div class="q-meta-row"><span class="q-status">手書き ${inkCount}ストローク${grade?' / 採点 '+gradeLabel(grade):''}</span></div></section>`}
function renderPractice(){const p=packById(state.activePackId);if(!p){flushPageTimer();$('#practiceEmpty').classList.remove('hidden');$('#practiceArea').classList.add('hidden');return}const pr=ensureProgressExtras();$('#practiceEmpty').classList.add('hidden');$('#practiceArea').classList.remove('hidden');currentPage=Math.min(pr.currentPage||currentPage,Math.max(0,Math.ceil(p.questions.length/PAGE_SIZE)-1));pr.currentPage=currentPage;$('#practiceSource').textContent=`${p.source} · ${p.level} · ${p.focus}`;$('#practiceTitle').textContent=p.title+(pr.reviewMode?'｜答え合わせ':'');$('#practiceDesc').textContent=pr.reviewMode?'紙面はそのまま。下の正答基準を見て○/△/×と「どこで迷ったか」を残してください。':p.description;$('#paperTitle').textContent=p.title;const totalPages=Math.ceil(p.questions.length/PAGE_SIZE);$('#pageNow').textContent=currentPage+1;$('#pageTotal').textContent=totalPages;$('#paperPageLabel').textContent=`Page ${currentPage+1} / ${totalPages}`;$('#prevPageBtn').disabled=currentPage===0;$('#nextPageBtn').disabled=currentPage>=totalPages-1;const qs=p.questions.slice(currentPage*PAGE_SIZE,(currentPage+1)*PAGE_SIZE);$('#questionList').innerHTML=qs.map((q,i)=>renderQuestion(q,currentPage*PAGE_SIZE+i+1)).join('');renderReviewPanel(qs);bindQuestions();updatePracticeProgress();updateFinishButton();setMode('pen',false);save();setTimeout(()=>{resizeCanvas();renderInk();startPageTimer()},20)}
function answerBasis(q){if(q.type==='choice')return q.answer||'';if(q.type==='fields')return(q.fields||[]).map(f=>`${f.label}: ${(f.answers||[]).join(' / ')}`).join(' ｜ ');if(q.type==='reorder')return q.answer||q.guide||'';if(q.type==='passage')return(q.answers||[]).map((a,i)=>`${i+1}. ${a}`).join(' ｜ ')||q.guide||'ChatGPT確認';return q.guide||'自由記述（ChatGPT確認）'}
function correctAnswerText(q){return answerBasis(q)}
function renderReviewPanel(qs){const host=$('#reviewPanel'),pr=ensureProgressExtras();if(!host)return;if(!pr.reviewMode){host.classList.add('hidden');host.innerHTML='';return}host.classList.remove('hidden');host.innerHTML=`<div class="review-panel-head"><div><span>ANSWER CHECK</span><strong>このページの答え合わせ</strong></div><small>△・×では、理由タグも残すとChatGPTが癖を追いやすくなります。</small></div><div class="review-answer-list">${qs.map((q,i)=>{const grade=pr.selfGrades[q.id]||'',tags=pr.reviewTags[q.id]||[],note=pr.reviewNotes[q.id]||'',manual=q.type==='manual'||(q.type==='passage'&&q.manualReview);return `<div class="review-answer-item"><b>${currentPage*PAGE_SIZE+i+1}.</b><div><span>${manual?'確認基準':'正答'}：${esc(answerBasis(q))}</span>${q.guide?`<small>${esc(q.guide)}</small>`:''}</div>${manual?'<em>AI確認</em>':`<div class="grade-row">${[['correct','○'],['partial','△'],['wrong','×']].map(([v,l])=>`<button class="grade-btn ${grade===v?'active '+v:''}" data-grade-qid="${q.id}" data-grade="${v}">${l}</button>`).join('')}</div>`}${grade&&grade!=='correct'?`<div class="review-extra">${MISTAKE_TAGS.map(([v,l])=>`<button class="mistake-tag ${tags.includes(v)?'active':''}" data-tag-qid="${q.id}" data-tag="${v}" type="button">${l}</button>`).join('')}</div><textarea class="review-note-input" data-review-note="${q.id}" placeholder="任意：何を勘違いした？ どこで迷った？">${esc(note)}</textarea>`:''}</div>`}).join('')}</div>`}
function bindQuestions(){$$('[data-grade-qid]').forEach(b=>b.onclick=()=>{const pr=ensureProgressExtras(),qid=b.dataset.gradeQid;pr.selfGrades[qid]=b.dataset.grade;if(b.dataset.grade==='correct'){pr.reviewTags[qid]=[];pr.reviewNotes[qid]=''}save();renderPractice()});$$('[data-tag-qid]').forEach(b=>b.onclick=()=>{const pr=ensureProgressExtras(),qid=b.dataset.tagQid;pr.reviewTags[qid]??=[];const arr=pr.reviewTags[qid],tag=b.dataset.tag,at=arr.indexOf(tag);if(at>=0)arr.splice(at,1);else arr.push(tag);save();b.classList.toggle('active',arr.includes(tag))});$$('[data-review-note]').forEach(el=>el.onchange=()=>{ensureProgressExtras().reviewNotes[el.dataset.reviewNote]=el.value.trim();save()})}
function updatePracticeProgress(){const p=packById(state.activePackId),n=answerCount(p.id),pr=ensureProgressExtras();$('#practiceProgress').textContent=`${n}/${p.questions.length}`;const lab=$('#practiceProgress').nextElementSibling;if(lab)lab.textContent=pr.reviewMode?'自己採点・確認':'書き込みあり';updatePageTimeLabel()}
function updateFinishButton(){if($('#finishBtn'))$('#finishBtn').textContent=ensureProgressExtras().reviewMode?'自己採点を保存して結果へ':'答え合わせへ'}
function changePage(d){const p=packById(state.activePackId),pages=Math.ceil(p.questions.length/PAGE_SIZE),next=Math.max(0,Math.min(pages-1,currentPage+d));if(next===currentPage)return;flushPageTimer();currentPage=next;ensureProgressExtras().currentPage=currentPage;save();renderPractice();scrollTo({top:0,behavior:'smooth'})}
function saveSnapshot(){flushPageTimer();const pr=ensureProgressExtras();pr.snapshots.push({time:new Date().toISOString(),page:currentPage,selfGrades:structuredClone(pr.selfGrades),reviewTags:structuredClone(pr.reviewTags),inkStrokeCount:Object.values(pr.inkPages||{}).reduce((n,a)=>n+a.length,0),pageTimeMs:structuredClone(pr.pageTimeMs)});if(pr.snapshots.length>30)pr.snapshots=pr.snapshots.slice(-30);save();startPageTimer();toast('現在の手書き状態を記録しました')}
function finishPackAction(){const pr=ensureProgressExtras();if(!pr.reviewMode){flushPageTimer();pr.reviewMode=true;currentPage=0;pr.currentPage=0;save();renderPractice();scrollTo({top:0,behavior:'smooth'});toast('答え合わせへ移りました');return}finalizeReview()}
function finalizeReview(){flushPageTimer();const p=packById(state.activePackId),pr=ensureProgressExtras();if(!p)return;const gradable=p.questions.filter(q=>q.type!=='manual'&&!(q.type==='passage'&&q.manualReview)),missing=gradable.filter(q=>!pr.selfGrades[q.id]);if(missing.length&&!confirm(`${missing.length}問が未採点です。未採点は0点として保存しますか？`)){startPageTimer();return}const results=p.questions.map(q=>{const manual=q.type==='manual'||(q.type==='passage'&&q.manualReview),grade=manual?'manual':(pr.selfGrades[q.id]||'ungraded'),points=grade==='correct'?1:grade==='partial'?.5:0;return {questionId:q.id,originQuestionId:q.originQuestionId||null,originPackId:q.originPackId||null,type:q.type,skill:q.skill,prompt:q.prompt,sentence:q.sentence||q.passage||'',correctAnswer:answerBasis(q),selfGrade:grade,points,correct:grade==='correct'?true:grade==='wrong'||grade==='ungraded'?false:null,reviewTags:[...(pr.reviewTags[q.id]||[])],reviewNote:pr.reviewNotes[q.id]||'',inkStrokeCount:inkCountForQuestion(pr,q.id)}});const scored=results.filter(r=>r.selfGrade!=='manual'),pointTotal=scored.reduce((n,r)=>n+r.points,0),score=scored.length?Math.round(pointTotal/scored.length*100):0,skills={};for(const r of scored){skills[r.skill]??={points:0,total:0};skills[r.skill].total++;skills[r.skill].points+=r.points}const durationMs=Object.values(pr.pageTimeMs||{}).reduce((n,v)=>n+v,0),session={id:id(),attemptId:pr.attemptId,finishedAt:new Date().toISOString(),startedAt:pr.startedAt,packId:p.id,packTitle:p.title,source:p.source,score,autoCorrect:scored.filter(r=>r.selfGrade==='correct').length,autoPartial:scored.filter(r=>r.selfGrade==='partial').length,autoWrong:scored.filter(r=>r.selfGrade==='wrong'||r.selfGrade==='ungraded').length,autoTotal:scored.length,manualCount:results.filter(r=>r.selfGrade==='manual').length,results,skillScores:Object.fromEntries(Object.entries(skills).map(([k,v])=>[k,Math.round(v.points/v.total*100)])),snapshots:pr.snapshots.length,totalInk:Object.values(pr.inkPages||{}).reduce((n,a)=>n+a.length,0),pageTimeMs:structuredClone(pr.pageTimeMs),durationMs,paperBased:true,appVersion:APP_BUILD.version,build:APP_BUILD.build};state.sessions.unshift(session);if(state.sessions.length>120)state.sessions=state.sessions.slice(0,120);pr.completedAt=session.finishedAt;pr.lastScore=score;pr.reviewMode=false;save();renderLibrary();openView('results');toast('自己採点結果を保存しました')}
