import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8'),json=p=>JSON.parse(read(p)),assert=(x,m)=>{if(!x)throw new Error(m)};
const manifest=json('data/packs/index.json'),pedagogy=json('data/pedagogy.json');assert(manifest.paperSchemaVersion===6,'paperSchemaVersion must be 6');assert(manifest.expectedCounts?.packs&&manifest.expectedCounts?.questions,'expectedCounts missing');assert(pedagogy.modes?.skeleton&&pedagogy.modes?.range&&pedagogy.modes?.structure,'pedagogy modes missing');
const packs=manifest.files.flatMap(f=>json('data/packs/'+f)),questions=packs.flatMap(p=>p.questions.map(q=>({p,q})));assert(packs.length===manifest.expectedCounts.packs,`pack count ${packs.length}`);assert(questions.length===manifest.expectedCounts.questions,`question count ${questions.length}`);const pids=packs.map(p=>p.id),qids=questions.map(x=>x.q.id);assert(new Set(pids).size===pids.length,'duplicate pack id');assert(new Set(qids).size===qids.length,'duplicate question id');
const types=new Set(['fields','choice','manual','reorder','passage']),modes=new Set(Object.keys(pedagogy.modes));for(const{p,q}of questions){assert(q.id&&q.prompt&&q.skill,`${p.id}: missing fields ${q.id}`);assert(types.has(q.type),`${q.id}: unsupported type`);if(q.studyMode)assert(modes.has(q.studyMode),`${q.id}: invalid studyMode`);if(q.type==='choice')assert(Array.isArray(q.choices)&&q.choices.includes(q.answer),`${q.id}: bad choice`);if(q.type==='fields')for(const f of q.fields||[])assert(f.id&&f.label&&Array.isArray(f.answers)&&f.answers.length,`${q.id}: bad field`)}
const curriculum=json('data/curriculum.json');assert(pids.every(id=>curriculum.packs?.[id]),'pack missing in curriculum');json('data/analysis-return.schema.json');json('data/legacy/foundation-sv-v051.json');json('data/legacy/sv-phrase-boundary-v051.json');
const html=read('index.html'),refs=[...html.matchAll(/(?:src|href)="\.\/([^"?#]+)(?:\?[^"#]*)?"/g)].map(m=>m[1]);for(const r of refs)assert(fs.existsSync(path.join(root,r)),`broken ref ${r}`);assert(refs.includes('js/v060/app.js'),'v060 app not loaded');assert(refs.includes('css/app-v060.css'),'v060 css not loaded');assert(!refs.some(r=>/v050|v053|v054|v055|practice\.js$|ink\.js$/.test(r)),'legacy patch runtime file is still loaded');
for(const f of['js/v060/db.js','js/v060/state.js','js/v060/data.js','js/v060/library.js','js/v060/practice.js','js/v060/ink.js','js/v060/results.js','js/v060/analysis.js','js/v060/export.js','js/v060/app.js'])assert(fs.existsSync(path.join(root,f)),`missing ${f}`);
const app=read('js/v060/app.js'),ink=read('js/v060/ink.js'),state=read('js/v060/state.js');assert(ink.includes('getQuestionInk')&&ink.includes('questionId'),'question-local ink missing');assert(state.includes('paperSnapshotId')&&state.includes('paperRevision'),'paper snapshot missing');assert(app.includes('expectedCounts')&&!app.includes('===14')&&!app.includes('===188'),'diagnostic hardcode remains');
console.log(`OK v0.6: ${packs.length} packs / ${questions.length} questions / ${refs.length} runtime refs`);
