import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),json=p=>JSON.parse(read(p)),assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const manifest=json('data/packs/index.json');assert(Array.isArray(manifest.files)&&manifest.files.length,'packs/index.json files が空です');const packs=manifest.files.flatMap(f=>json('data/packs/'+f));assert(packs.length===15,`問題セット数が15ではありません: ${packs.length}`);const questions=packs.flatMap(p=>p.questions.map(q=>({pack:p,q})));assert(questions.length===200,`問題数が200ではありません: ${questions.length}`);const packIds=packs.map(p=>p.id),qIds=questions.map(x=>x.q.id);assert(new Set(packIds).size===packIds.length,'問題セットIDが重複しています');assert(new Set(qIds).size===qIds.length,'問題IDが重複しています');
const validTypes=new Set(['fields','choice','manual','reorder','passage']),validStudyModes=new Set(['skeleton','range','structure']);for(const{pack,q}of questions){assert(q.id&&q.prompt&&q.skill,`${pack.id}: 問題の必須項目不足 ${q.id||'(no id)'}`);assert(validTypes.has(q.type),`${q.id}: 未対応type ${q.type}`);if(q.studyMode)assert(validStudyModes.has(q.studyMode),`${q.id}: studyMode不正 ${q.studyMode}`);if(q.type==='choice'){assert(Array.isArray(q.choices)&&q.choices.length>=2,`${q.id}: choices不足`);assert(q.choices.includes(q.answer),`${q.id}: answerがchoicesにありません`)}if(q.type==='fields'){assert(Array.isArray(q.fields)&&q.fields.length,`${q.id}: fields不足`);for(const f of q.fields)assert(f.id&&f.label&&Array.isArray(f.answers)&&f.answers.length,`${q.id}: field正答基準不足`)}if(q.type==='reorder'){assert(Array.isArray(q.words)&&q.words.length>=2&&q.answer,`${q.id}: reorder不足`)}if(q.type==='passage'){assert(q.passage&&Array.isArray(q.tasks)&&Array.isArray(q.answers)&&q.tasks.length===q.answers.length&&q.tasks.length,`${q.id}: passage tasks/answers不整合`)}}
for(const p of packs)if(p.defaultStudyMode)assert(validStudyModes.has(p.defaultStudyMode),`${p.id}: defaultStudyMode不正`);
const curriculum=json('data/curriculum.json'),curriculumIds=Object.keys(curriculum.packs||{});assert(packIds.every(id=>curriculumIds.includes(id)),'curriculumに存在しない問題セットがあります');assert(curriculumIds.every(id=>packIds.includes(id)),'curriculumに問題データのないIDがあります');for(const phase of curriculum.phases||[])for(const id of phase.packIds||[])assert(packIds.includes(id),`phase ${phase.id} が不明pack ${id} を参照しています`);
json('data/analysis-return.schema.json');const html=read('index.html'),refs=[...html.matchAll(/(?:src|href)="\.\/([^"?#]+)(?:\?[^"#]*)?"/g)].map(m=>m[1]);for(const ref of refs)assert(fs.existsSync(path.join(root,ref)),`index.html参照切れ: ${ref}`);for(const must of['js/version.js','js/core.js','js/practice.js','js/results-analysis.js','js/ink.js','js/export-zip.js','js/product-v050.js','js/pedagogy-v053.js','js/review-geometry-v054.js','js/paper-schema-v055.js','css/styles.css','css/paper-v041.css','css/product-v050.css','css/review-split-v052.css','css/pedagogy-v053.css','css/paper-schema-v055.css'])assert(fs.existsSync(path.join(root,must)),`主要ファイル不足: ${must}`);
const sentenceCounts=new Map();for(const{q}of questions){const text=(q.sentence||q.passage||'').trim();if(text)sentenceCounts.set(text,(sentenceCounts.get(text)||0)+1)}const excessive=[...sentenceCounts].filter(([,n])=>n>3);assert(!excessive.length,`同一英文の過剰反復: ${excessive.map(([s,n])=>`${n}x ${s.slice(0,50)}`).join(' / ')}`);
assert(packIds.includes('sv-phrase-boundary'),'ChatGPT弱点補強セットがありません');const adaptive=packs.find(p=>p.id==='sv-phrase-boundary');assert(adaptive.questions.length===12,'S/V補強セットは12問である必要があります');const foundation=packs.find(p=>p.id==='foundation-sv');assert(foundation?.defaultStudyMode==='skeleton','foundation-svは骨格読みを既定にする必要があります');const sv09=foundation.questions.find(q=>q.id==='sv09');assert(sv09.fields.find(f=>f.id==='v').answers.includes('has been checked'),'sv09のVは副詞alreadyを除いたhas been checkedである必要があります');const pb03=adaptive.questions.find(q=>q.id==='pb03');assert(pb03.studyMode==='skeleton'&&pb03.fields.find(f=>f.id==='s').answers.includes('Reading'),'pb03はReadingを骨格Sとして許容する必要があります');const pb08=adaptive.questions.find(q=>q.id==='pb08');assert(pb08.fields.find(f=>f.id==='v').answers.includes('has been')&&pb08.fields.find(f=>f.id==='c').answers.includes('absent'),'pb08はV=has been / C=absentで分ける必要があります');
const schemaJs=read('js/paper-schema-v055.js');assert(schemaJs.includes("LEGACY_REV='v051-paper'"),'旧紙面Revisionが定義されていません');assert(schemaJs.includes("id:'pb01'")&&schemaJs.includes("label:'S全体'")&&!schemaJs.includes("id:'pb01',type:'fields',prompt:'【範囲問題】"),'pb01旧紙面が復元できません');assert(schemaJs.includes("paperRevision")&&schemaJs.includes("reviewAnswer"),'紙面Revision/正答補正がありません');assert(read('css/paper-schema-v055.css').includes('.paper-schema-v051 .q-mode-row'),'旧紙面で追加UIをレイアウトから外すCSSがありません');
console.log(`OK: ${packs.length} packs / ${questions.length} questions / ${refs.length} local refs / immutable paper schema v0.5.5`);
