import {APP,state,prefs,updatePrefs,esc,stateForExport} from './state.js';
import {catalog,getAttemptPack} from './data.js';
import {PAGE_SIZE} from './practice.js';
import {getQuestionStrokesForExport,drawStroke} from './ink.js';
import {getLegacyPageInk,exportAttemptInk,estimateDb} from './db.js';

let cssCache='';
const $=s=>document.querySelector(s);
function safeName(v){return String(v||'worksheet').replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_').slice(0,70)}
function utf8(s){return new TextEncoder().encode(s)}
let crcTable=null;function crc32(bytes){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
const u16=v=>[v&255,(v>>>8)&255],u32=v=>[v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255];
function dos(d=new Date()){const y=Math.max(1980,d.getFullYear());return{time:(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),date:((y-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate()}}
async function entry(name,data){const bytes=data instanceof Uint8Array?data:data instanceof Blob?new Uint8Array(await data.arrayBuffer()):utf8(String(data));return{name,bytes,crc:crc32(bytes)}}
async function zip(files){const es=[];for(const f of files)es.push(await entry(f.name,f.data));const chunks=[],central=[];let offset=0;const td=dos();for(const e of es){const n=utf8(e.name),size=e.bytes.length,local=new Uint8Array([80,75,3,4,...u16(20),...u16(0x800),...u16(0),...u16(td.time),...u16(td.date),...u32(e.crc),...u32(size),...u32(size),...u16(n.length),0,0,...n]);chunks.push(local,e.bytes);central.push(new Uint8Array([80,75,1,2,...u16(20),...u16(20),...u16(0x800),...u16(0),...u16(td.time),...u16(td.date),...u32(e.crc),...u32(size),...u32(size),...u16(n.length),0,0,0,0,0,0,0,0,0,0,...u32(offset),...n]));offset+=local.length+size}const csize=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array([80,75,5,6,0,0,0,0,...u16(es.length),...u16(es.length),...u32(csize),...u32(offset),0,0]);return new Blob([...chunks,...central,end],{type:'application/zip'})}

async function css(){if(cssCache)return cssCache;const r=await fetch(`./css/app-v060.css?b=${APP.build}`,{cache:'no-store'});cssCache=await r.text();return cssCache}
function pageQuestions(pack,page){return pack.questions.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE)}
function questionHtml(q,num){let answer='';if(q.type==='fields')answer=`<div class="paper-answer-lines">${(q.fields||[]).map(f=>`<div class="paper-line-field"><span>${esc(f.label)}</span><i></i></div>`).join('')}</div>`;else if(q.type==='choice')answer=`<div class="paper-choice-list">${(q.choices||[]).map((c,i)=>`<div><b>${String.fromCharCode(65+i)}.</b><span>${esc(c)}</span></div>`).join('')}</div>`;else answer=`<div class="paper-writing-lines">${'<i></i>'.repeat(q.lines||4)}</div>`;return `<section class="question" data-question-id="${q.id}"><span class="q-num">${num}.</span><div class="q-content"><div class="q-prompt">${esc(q.prompt)}</div>${q.sentence?`<div class="q-sentence">${esc(q.sentence)}</div>`:''}${answer}</div><canvas class="question-ink" data-question-id="${q.id}"></canvas></section>`}
async function renderPaper(pack,pr,page){const paper=document.createElement('article');paper.className='paper export-paper'+(pr.legacyLayout?' legacy-paper':'');paper.style.position='fixed';paper.style.left='-20000px';paper.style.top='0';paper.style.width='950px';paper.innerHTML=`<div class="paper-header"><div><span>English Worksheet Lab</span><strong>${esc(pack.title)}</strong></div><div class="paper-meta"><span>名前</span><span>Page ${page+1}</span></div></div><div class="paper-rule"><strong>基本:</strong> 修飾は後回しにして骨格を先に取る。</div><div class="question-list">${pageQuestions(pack,page).map((q,i)=>questionHtml(q,page*PAGE_SIZE+i+1)).join('')}</div><canvas class="legacy-ink-canvas"></canvas>`;document.body.append(paper);await document.fonts?.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
  for(const canvas of paper.querySelectorAll('.question-ink')){const q=canvas.closest('.question'),w=q.clientWidth,h=q.clientHeight,ratio=1.5;canvas.width=w*ratio;canvas.height=h*ratio;canvas.style.width=w+'px';canvas.style.height=h+'px';const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);const strokes=await getQuestionStrokesForExport(pr.attemptId,canvas.dataset.questionId);for(const s of strokes)drawStroke(ctx,s,w,h)}
  if(pr.legacyLayout){const c=paper.querySelector('.legacy-ink-canvas'),w=paper.clientWidth,h=paper.scrollHeight,ratio=1.5;c.width=w*ratio;c.height=h*ratio;c.style.width=w+'px';c.style.height=h+'px';const ctx=c.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);for(const s of await getLegacyPageInk(pr.attemptId,page))drawStroke(ctx,s,w,h)}
  const width=paper.clientWidth,height=paper.scrollHeight,clone=paper.cloneNode(true);clone.style.position='relative';clone.style.left='0';clone.style.width=width+'px';for(const pair of [...paper.querySelectorAll('canvas')].map((c,i)=>[c,clone.querySelectorAll('canvas')[i]])){const [src,dst]=pair;if(!dst)continue;const img=document.createElement('img');img.src=src.toDataURL('image/png');img.className=dst.className;img.style.cssText=dst.style.cssText;dst.replaceWith(img)}paper.remove();const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width',width);svg.setAttribute('height',height);const fo=document.createElementNS('http://www.w3.org/2000/svg','foreignObject');fo.setAttribute('width','100%');fo.setAttribute('height','100%');const wrap=document.createElementNS('http://www.w3.org/1999/xhtml','div');wrap.setAttribute('xmlns','http://www.w3.org/1999/xhtml');const st=document.createElement('style');st.textContent=await css()+`\nbody{margin:0}.export-paper{margin:0!important;box-shadow:none!important;transform:none!important}`;wrap.append(st,clone);fo.append(wrap);svg.append(fo);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}));try{const im=await new Promise((res,rej)=>{const x=new Image();x.onload=()=>res(x);x.onerror=rej;x.src=url}),out=document.createElement('canvas'),scale=1.5;out.width=width*scale;out.height=height*scale;const ctx=out.getContext('2d');ctx.scale(scale,scale);ctx.fillStyle='#fbfbf8';ctx.fillRect(0,0,width,height);ctx.drawImage(im,0,0,width,height);return await new Promise((res,rej)=>out.toBlob(b=>b?res(b):rej(new Error('PNG生成失敗')),'image/png'))}finally{URL.revokeObjectURL(url)}}

function targetProgress(scope){const all=Object.values(state.packProgress).filter(x=>x.touchedQuestions?.length||Object.keys(x.selfGrades||{}).length);if(scope==='all')return all;if(scope==='recent3'){const ids=new Set(state.sessions.slice(0,3).map(s=>s.attemptId));return all.filter(x=>ids.has(x.attemptId))}const current=state.activePackId?state.packProgress[state.activePackId]:null;return current?[current]:all.slice(0,1)}
export function analysisPrompt(){return `添付ZIPはペンタブで解いた英語問題集です。最重要は papers/ のPNGです。最終正誤だけでなく、下線・丸・括弧・矢印・消去履歴から途中の読み方を分析してください。\n\n${catalog.pedagogy.analysisInstruction}\n\n特に、主節S/V、節境界、O/C、時制、to/ing、前置詞の核イメージ、正解していても危ない読み方、書き直しの共通パターンを確認してください。最後にanalysis-return.schema.jsonと同形式のJSONを返してください。`;}

export async function downloadSubmission(scope=prefs.exportScope||'current'){$('#exportStatus').textContent='ZIP作成中…';updatePrefs({exportScope:scope});const prs=targetProgress(scope);if(!prs.length){$('#exportStatus').textContent='提出できる紙がありません';return}const files=[],pages=[],snapshots=[];for(const pr of prs){const pack=await getAttemptPack(pr);if(!pack)continue;snapshots.push({attemptId:pr.attemptId,paperRevision:pr.paperRevision,pack});const pageSet=new Set();for(const qid of pr.touchedQuestions||[]){const i=pack.questions.findIndex(q=>q.id===qid);if(i>=0)pageSet.add(Math.floor(i/PAGE_SIZE))}for(const qid of Object.keys(pr.selfGrades||{})){const i=pack.questions.findIndex(q=>q.id===qid);if(i>=0)pageSet.add(Math.floor(i/PAGE_SIZE))}for(const page of [...pageSet].sort((a,b)=>a-b)){const blob=await renderPaper(pack,pr,page),name=`papers/${safeName(pack.title)}_${pr.attemptId.slice(0,8)}_p${String(page+1).padStart(2,'0')}.png`;files.push({name,data:blob});pages.push({file:name,packId:pack.id,packTitle:pack.title,attemptId:pr.attemptId,paperRevision:pr.paperRevision,page:page+1,questions:pageQuestions(pack,page).map((q,i)=>({number:page*PAGE_SIZE+i+1,questionId:q.id,selfGrade:pr.selfGrades[q.id]||null,reviewTags:pr.reviewTags[q.id]||[],reviewNote:pr.reviewNotes[q.id]||''}))})}}
  const attemptIds=prs.map(x=>x.attemptId),ink=await exportAttemptInk(attemptIds),storage=await estimateDb(),manifest={package:'english-worksheet-submission',packageVersion:APP.submissionPackage,createdAt:new Date().toISOString(),scope,app:APP,counts:{attempts:prs.length,pages:pages.length},analysisOrder:['papers/','ink-history.json','paper-index.json','learning-data.json','paper-snapshots.json']};files.push({name:'paper-index.json',data:JSON.stringify({schemaVersion:2,pages},null,2)},{name:'paper-snapshots.json',data:JSON.stringify(snapshots,null,2)},{name:'ink-history.json',data:JSON.stringify(ink,null,2)},{name:'learning-data.json',data:JSON.stringify({schemaVersion:6,app:APP,state:stateForExport(),curriculum:catalog.curriculum,pedagogy:catalog.pedagogy,storage},null,2)},{name:'questions.json',data:JSON.stringify(snapshots.map(x=>x.pack),null,2)},{name:'analysis-return.schema.json',data:await fetch('./data/analysis-return.schema.json').then(r=>r.text())},{name:'ChatGPTに見てほしいこと.txt',data:analysisPrompt()});manifest.files=files.map(f=>f.name);files.push({name:'manifest.json',data:JSON.stringify(manifest,null,2)});const blob=await zip(files),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`english_submission_${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200);$('#exportStatus').textContent=`ZIP作成完了 (${pages.length}ページ)`}
