import {state,progress,saveState,esc,markTouched} from './state.js';
import {getAttemptPack,questionMode,answerBasis,catalog} from './data.js';
import {bindInkCanvases,renderAllInk} from './ink.js';

export const PAGE_SIZE=10;
export const MISTAKE_TAGS=[['subject','Sを取り違えた'],['verb','Vを取り違えた'],['clause','節の境界'],['modifier','修飾を骨格に入れた'],['oc','O/C・文型'],['tense','時制・時間軸'],['verbform','to / ing'],['preposition','前置詞イメージ'],['wordorder','語順'],['vocab','単語'],['question','設問読み違い'],['unknown','分からなかった']];
let timer=null,onResults=null,onLibrary=null;

const $=s=>document.querySelector(s);
export const gradeLabel=g=>({correct:'○',partial:'△',wrong:'×',ungraded:'未採点',manual:'AI確認'})[g]||g;
export function formatDuration(ms){const sec=Math.max(0,Math.round((ms||0)/1000)),m=Math.floor(sec/60),s=sec%60;return m?`${m}分${String(s).padStart(2,'0')}秒`:`${s}秒`}

function flushTimer(){if(!timer)return;const pr=progress(timer.packId);if(pr){pr.pageTimeMs[timer.page]=(pr.pageTimeMs[timer.page]||0)+Math.max(0,performance.now()-timer.started)}timer=null;saveState()}
function startTimer(){const pr=progress();if(!pr)return;flushTimer();timer={packId:state.activePackId,page:pr.currentPage||0,started:performance.now()};updateTimer()}
function elapsed(){const pr=progress();if(!pr)return 0;return(pr.pageTimeMs[pr.currentPage]||0)+(timer&&timer.packId===state.activePackId&&timer.page===pr.currentPage?performance.now()-timer.started:0)}
function updateTimer(){const el=$('#pageTimeLabel');if(el)el.textContent=`このページ ${formatDuration(elapsed())}`}
setInterval(()=>timer&&updateTimer(),1000);

function paperLines(count=4,compact=false){return `<div class="paper-writing-lines ${compact?'compact':''}">${'<i></i>'.repeat(count)}</div>`}
function answerArea(q){
  if(q.type==='fields')return `<div class="paper-answer-lines">${(q.fields||[]).map(f=>`<div class="paper-line-field"><span>${esc(f.label)}</span><i></i></div>`).join('')}</div>`;
  if(q.type==='choice')return `<div class="paper-choice-list">${(q.choices||[]).map((c,i)=>`<div><b>${String.fromCharCode(65+i)}.</b><span>${esc(c)}</span></div>`).join('')}</div>`;
  if(q.type==='reorder')return `<div class="reorder-words">${(q.words||[]).map(w=>`<span>${esc(w)}</span>`).join('')}</div>${paperLines(q.lines||2,true)}`;
  if(q.type==='passage')return `<div class="passage-box">${esc(q.passage||'')}</div><div class="passage-tasks">${(q.tasks||[]).map((t,i)=>`<div><b>${i+1}.</b> ${esc(t)}</div>`).join('')}</div>${paperLines(q.lines||6)}`;
  return paperLines(q.lines||4);
}
export function questionMarkup(q,num){return `<section class="question" data-question-id="${esc(q.id)}"><span class="q-num">${num}.</span><div class="q-content"><div class="q-prompt">${esc(q.prompt)}</div>${q.visual?`<div class="question-visual">${esc(q.visual)}</div>`:''}${q.sentence?`<div class="q-sentence">${esc(q.sentence)}</div>`:''}${answerArea(q)}</div><canvas class="question-ink" data-question-id="${esc(q.id)}" aria-label="問${num}への手書き"></canvas></section>`}

export function paperInnerMarkup(pack,page){const qs=pack.questions.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);const totalPages=Math.ceil(pack.questions.length/PAGE_SIZE);return `<div class="paper-header"><div><span>English Worksheet Lab</span><strong>${esc(pack.title)}</strong></div><div class="paper-meta"><span>名前</span><span>Page ${page+1} / ${totalPages}</span></div></div><div class="paper-rule"><strong>基本:</strong> 修飾は後回しにして骨格を先に取る。範囲を聞かれた問題だけ端まで確認する。</div><div class="question-list">${qs.map((q,i)=>questionMarkup(q,page*PAGE_SIZE+i+1)).join('')}</div><canvas id="legacyInkCanvas" class="legacy-ink-canvas" aria-hidden="true"></canvas>`}

export async function initPractice({onOpenResults,onRenderLibrary}){onResults=onOpenResults;onLibrary=onRenderLibrary;$('#prevPageBtn').onclick=()=>changePage(-1);$('#nextPageBtn').onclick=()=>changePage(1);$('#finishBtn').onclick=finishAction;$('#saveSnapshotBtn').onclick=saveSnapshot;}

export async function renderPractice(){
  const pr=progress();if(!pr){$('#practiceEmpty').classList.remove('hidden');$('#practiceArea').classList.add('hidden');flushTimer();return}
  const pack=await getAttemptPack(pr);if(!pack)return;
  const max=Math.max(0,Math.ceil(pack.questions.length/PAGE_SIZE)-1);pr.currentPage=Math.min(pr.currentPage||0,max);
  $('#practiceEmpty').classList.add('hidden');$('#practiceArea').classList.remove('hidden');$('#practiceSource').textContent=`${pack.source} · ${pack.level} · ${pack.focus}`;$('#practiceTitle').textContent=pack.title+(pr.reviewMode?'｜答え合わせ':'');$('#practiceDesc').textContent=pr.reviewMode?'左の紙は一切組み替えません。右だけをスクロールして答え合わせします。':pack.description;
  $('#paper').classList.toggle('legacy-paper',!!pr.legacyLayout);$('#paper').innerHTML=paperInnerMarkup(pack,pr.currentPage);$('#pageNow').textContent=pr.currentPage+1;$('#pageTotal').textContent=Math.ceil(pack.questions.length/PAGE_SIZE);$('#prevPageBtn').disabled=pr.currentPage===0;$('#nextPageBtn').disabled=pr.currentPage===max;
  renderReview(pack,pr);updateProgress(pack,pr);document.body.classList.toggle('reviewing',!!pr.reviewMode);$('#finishBtn').textContent=pr.reviewMode?'自己採点を保存して結果へ':'答え合わせへ';
  bindInkCanvases();await renderAllInk();startTimer();saveState();
}

function updateProgress(pack,pr){const n=pack.questions.filter(q=>pr.touchedQuestions.includes(q.id)||pr.selfGrades[q.id]).length;$('#practiceProgress').textContent=`${n}/${pack.questions.length}`;updateTimer()}

function renderReview(pack,pr){const host=$('#reviewPanel');if(!pr.reviewMode){host.classList.add('hidden');host.innerHTML='';return}host.classList.remove('hidden');const qs=pack.questions.slice(pr.currentPage*PAGE_SIZE,(pr.currentPage+1)*PAGE_SIZE);host.innerHTML=`<div class="review-head"><div><span>ANSWER CHECK</span><h3>このページの答え</h3></div><small>左の自分の紙と見比べる。説明はここにだけ出します。</small></div><div class="review-list">${qs.map((q,i)=>reviewItem(q,pr.currentPage*PAGE_SIZE+i+1,pr,pack)).join('')}</div>`;bindReview(host)}
function reviewItem(q,num,pr,pack){const grade=pr.selfGrades[q.id]||'',tags=pr.reviewTags[q.id]||[],note=pr.reviewNotes[q.id]||'',mode=questionMode(q,pack),meta=catalog.pedagogy.modes[mode];const manual=q.type==='manual'||(q.type==='passage'&&q.manualReview);return `<article class="review-item" data-review-qid="${q.id}"><div class="review-item-top"><button class="review-jump" data-jump-q="${q.id}">← 問${num}</button><span class="mode-badge ${mode}">${esc(meta?.label||mode)}</span></div><strong>${manual?'確認基準':'正答'}</strong><p class="review-answer">${esc(answerBasis(q))}</p>${q.note?`<p class="review-explain">${esc(q.note)}</p>`:''}${meta?.description?`<p class="review-mode-help">${esc(meta.description)}</p>`:''}${manual?'<div class="ai-check">ChatGPT確認</div>':`<div class="grade-row">${[['correct','○'],['partial','△'],['wrong','×']].map(([v,l])=>`<button class="grade ${grade===v?'active '+v:''}" data-grade="${v}" data-qid="${q.id}">${l}</button>`).join('')}</div>`}${grade&&grade!=='correct'?`<div class="tag-list">${MISTAKE_TAGS.map(([v,l])=>`<button class="tag ${tags.includes(v)?'active':''}" data-tag="${v}" data-qid="${q.id}">${l}</button>`).join('')}</div><textarea data-note="${q.id}" placeholder="何を勘違いした？">${esc(note)}</textarea>`:''}</article>`}
function bindReview(host){host.querySelectorAll('[data-grade]').forEach(b=>b.onclick=async()=>{const pr=progress();pr.selfGrades[b.dataset.qid]=b.dataset.grade;if(b.dataset.grade==='correct'){pr.reviewTags[b.dataset.qid]=[];pr.reviewNotes[b.dataset.qid]=''}markTouched(state.activePackId,b.dataset.qid);saveState(true);await renderPractice()});host.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{const pr=progress(),qid=b.dataset.qid;pr.reviewTags[qid]??=[];const a=pr.reviewTags[qid],i=a.indexOf(b.dataset.tag);i>=0?a.splice(i,1):a.push(b.dataset.tag);saveState();b.classList.toggle('active',a.includes(b.dataset.tag))});host.querySelectorAll('[data-note]').forEach(t=>t.onchange=()=>{progress().reviewNotes[t.dataset.note]=t.value.trim();saveState()});host.querySelectorAll('[data-jump-q]').forEach(b=>b.onclick=()=>focusQuestion(b.dataset.jumpQ))}
function focusQuestion(qid){const stage=$('#paperStage'),q=$(`.question[data-question-id="${qid}"]`);if(!stage||!q)return;stage.scrollTo({top:Math.max(0,q.offsetTop-20),behavior:'smooth'});q.classList.add('review-focus');setTimeout(()=>q.classList.remove('review-focus'),1200)}

async function changePage(delta){const pr=progress(),pack=await getAttemptPack(pr),max=Math.ceil(pack.questions.length/PAGE_SIZE)-1,next=Math.max(0,Math.min(max,pr.currentPage+delta));if(next===pr.currentPage)return;flushTimer();pr.currentPage=next;saveState(true);await renderPractice();$('#paperStage').scrollTop=0;$('#reviewPanel').scrollTop=0}
async function finishAction(){const pr=progress();if(!pr.reviewMode){flushTimer();pr.reviewMode=true;pr.currentPage=0;saveState(true);await renderPractice();return}await finalizeReview()}

async function finalizeReview(){flushTimer();const pr=progress(),pack=await getAttemptPack(pr);const manual=pack.questions.filter(q=>q.type==='manual'||(q.type==='passage'&&q.manualReview));const gradable=pack.questions.filter(q=>!manual.includes(q)),scoredQs=gradable.filter(q=>['correct','partial','wrong'].includes(pr.selfGrades[q.id]));const missing=gradable.length-scoredQs.length;if(missing&&!confirm(`${missing}問は未採点です。0点にせず今回の集計対象外として保存しますか？`)){startTimer();return}const results=pack.questions.map(q=>{const isManual=manual.includes(q),g=isManual?'manual':(pr.selfGrades[q.id]||'ungraded'),points=g==='correct'?1:g==='partial'?.5:0;return{questionId:q.id,type:q.type,skill:q.skill,prompt:q.prompt,sentence:q.sentence||q.passage||'',correctAnswer:answerBasis(q),selfGrade:g,points,reviewTags:[...(pr.reviewTags[q.id]||[])],reviewNote:pr.reviewNotes[q.id]||''}});const scored=results.filter(r=>['correct','partial','wrong'].includes(r.selfGrade)),score=scored.length?Math.round(scored.reduce((n,r)=>n+r.points,0)/scored.length*100):0,skills={};for(const r of scored){skills[r.skill]??={p:0,n:0};skills[r.skill].p+=r.points;skills[r.skill].n++}const manualDone=manual.filter(q=>pr.touchedQuestions.includes(q.id)).length,complete=missing===0&&manualDone===manual.length,durationMs=Object.values(pr.pageTimeMs).reduce((n,x)=>n+x,0);const session={id:crypto.randomUUID?.()||String(Date.now()),attemptId:pr.attemptId,finishedAt:new Date().toISOString(),startedAt:pr.startedAt,packId:pack.id,packTitle:pack.title,source:pack.source,paperRevision:pr.paperRevision,score,coverageDone:scored.length+manualDone,coverageTotal:pack.questions.length,coveragePercent:Math.round((scored.length+manualDone)/pack.questions.length*100),autoCorrect:scored.filter(x=>x.selfGrade==='correct').length,autoPartial:scored.filter(x=>x.selfGrade==='partial').length,autoWrong:scored.filter(x=>x.selfGrade==='wrong').length,autoTotal:scored.length,results,skillScores:Object.fromEntries(Object.entries(skills).map(([k,v])=>[k,Math.round(v.p/v.n*100)])),durationMs,appVersion:'v0.6.0'};state.sessions.unshift(session);state.sessions=state.sessions.slice(0,150);pr.completedAt=complete?session.finishedAt:null;pr.lastScore=score;pr.reviewMode=false;saveState(true);onLibrary?.();onResults?.();}

function saveSnapshot(){const pr=progress();pr.snapshots.push({time:new Date().toISOString(),page:pr.currentPage,selfGrades:structuredClone(pr.selfGrades),reviewTags:structuredClone(pr.reviewTags)});pr.snapshots=pr.snapshots.slice(-30);saveState(true)}
export function flushPracticeTimer(){flushTimer()}
